### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sandeshlasnapure** [fcannizzaro/jsoup-annotations#1]
How can parse html sequentially like

text
text
image
text

I want that data to be parsed as per sequence  

Thanks

**Comment by fcannizzaro** [comment]
are text elements ? or raw text ?

You could use [ForEach](https://github.com/fcannizzaro/jsoup-annotations#foreachstring-query), and use **\*** inside a container element.
   
```java
@ForEach("container *")
void iterate(Element element){
    // parse your element here
}
```
